name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # - name: Set up Node.js (or any other environment)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '14'
      
      # - name: Run tests
      #   run: |
      #     npm install
      #     npm test
          
      - name: Trigger master workflow (via dispatch)
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -d '{"ref": "master"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/master-workflow.yml/dispatches
