name: Trigger Master Workflow

on:
  push:
    branches:
      - dev

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Master Workflow on Dispatch
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'master.yml', # replace with your actual master workflow file name
              ref: 'master',
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
