name: Create Repository Variable

on:
  push:
    branches:
      - main

jobs:
  create-variable:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install GitHub CLI
    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli.repo | sudo tee /etc/apt/sources.list.d/github-cli.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C99B11DEB97541F0
        sudo apt update
        sudo apt install gh

    # Step 3: Authenticate GitHub CLI
    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< ${{ secrets.TOKEN }}
    
    # Step 4: Create the repository variable
    - name: Create repository variable
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/shubham-kshetre/setup_env/actions/variables \
          -f "name=NAME" -f "value=agent-k"
