# .github/workflows/main.yml
name: Run from Master for Dev Branch

on:
  push:
    branches:
      - main       # Trigger from master
  workflow_dispatch: # Allows manual trigger

jobs:
  run-for-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Check semantic apiVersion
        run: |
          # Check Github variable for semantic version, if not available create one with 0.0.0 value
          echo "Checking semantic version..."
          # Add your logic for checking or setting the version

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli.repo | sudo tee /etc/apt/sources.list.d/github-cli.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C99B11DEB97541F0
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.TOKEN }}

      - name: Create repository variable
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/variables \
            -f "name=apiVersion" -f "value=0.0.0"

